"""
Identifies the overall best TF-IDF configuration across all three models
(Section 4.1.3), using the results already generated by tfidf_ablation_study.py.

"Best for all models" means the configuration is shared by a single TfidfVectorizer,
so the fair way to rank the 18 configurations is to average each config's F1-score
across the 3 models trained on it - not to pick the single highest F1 among all
54 (config, model) rows, which would just surface one model's own best config.
"""
import os

import pandas as pd

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INPUT_PATH = os.path.join(BASE_DIR, "exploration", "ablation_results.csv")
OUTPUT_PATH = os.path.join(BASE_DIR, "exploration", "best_ablation_configuration_results.csv")

if __name__ == "__main__":
    df = pd.read_csv(INPUT_PATH)

    # group the 54 rows into their 18 configs, then average F1 across the 3 models sharing each config
    grouped = (
        df.groupby(["ngram_range", "stop_words", "max_features"], dropna=False)["f1"]
        .mean()
        .reset_index()
        .rename(columns={"f1": "mean_f1"})
        .sort_values("mean_f1", ascending=False)
    )
    grouped["mean_f1"] = grouped["mean_f1"].round(4)

    grouped.to_csv(OUTPUT_PATH, index=False)

    best = grouped.iloc[0]
    print("Configurations ranked by mean F1-score across the 3 models:\n")
    print(grouped.to_string(index=False))
    print(f"\nOverall best configuration: ngram_range={best['ngram_range']}, "
          f"stop_words={best['stop_words']}, max_features={best['max_features']} "
          f"(mean F1 = {best['mean_f1']})")
    print(f"\nSaved to {OUTPUT_PATH}")
